// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_plantmix_TMBExports
#include <TMB.hpp>
using namespace density;
using namespace tmbutils;
using namespace Eigen;
#include "include/helper.hpp"
#include "lm.hpp"
#include "GMA_SMA.hpp"
#include "DBV_SBV_crop_mix.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "lm") {
    return lm(this);
  } else if(model == "GMA_SMA") {
    return GMA_SMA(this);
  } else if(model == "DBV_SBV_crop_mix") {
    return DBV_SBV_crop_mix(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
