## For lmerZ()
barnames <- utils::getFromNamespace("barnames", "lme4")
RHSForm <- utils::getFromNamespace("RHSForm", "lme4")
"RHSForm<-" <- utils::getFromNamespace("RHSForm<-", "lme4")
checkArgs <- utils::getFromNamespace("checkArgs", "lme4")
checkCtrlLevels <- utils::getFromNamespace("checkCtrlLevels", "lme4")
checkFormulaData <- utils::getFromNamespace("checkFormulaData", "lme4")
checkNlevels <- utils::getFromNamespace("checkNlevels", "lme4")
checkScaleX <- utils::getFromNamespace("checkScaleX", "lme4")
checkZdims <- utils::getFromNamespace("checkZdims", "lme4")
checkZrank <- utils::getFromNamespace("checkZrank", "lme4")
chkRank.drop.cols <- utils::getFromNamespace("chkRank.drop.cols", "lme4")
getStart <- utils::getFromNamespace("getStart", "lme4")
mkBlist <- utils::getFromNamespace("mkBlist", "lme4")
reOnly <- utils::getFromNamespace("reOnly", "lme4")
